insert into public.categories (name, slug, sort_order) values
  ('Business & Strategy', 'business-strategy', 10),
  ('Finance', 'finance', 20),
  ('Marketing', 'marketing', 30),
  ('Sales', 'sales', 40),
  ('E-commerce', 'e-commerce', 50),
  ('Operations', 'operations', 60),
  ('Customer Service', 'customer-service', 70),
  ('Data Analysis', 'data-analysis', 80),
  ('Excel', 'excel', 90),
  ('Research', 'research', 100),
  ('Writing', 'writing', 110),
  ('Content Creation', 'content-creation', 120),
  ('Social Media', 'social-media', 130),
  ('SEO', 'seo', 140),
  ('Advertising', 'advertising', 150),
  ('Branding', 'branding', 160),
  ('Product Development', 'product-development', 170),
  ('AI Agents', 'ai-agents', 180),
  ('Automation', 'automation', 190),
  ('Coding', 'coding', 200),
  ('Software Development', 'software-development', 210),
  ('Prompt Engineering', 'prompt-engineering', 220),
  ('Education', 'education', 230),
  ('Learning', 'learning', 240),
  ('Human Resources', 'human-resources', 250),
  ('Legal', 'legal', 260),
  ('Healthcare', 'healthcare', 270),
  ('Productivity', 'productivity', 280),
  ('Image Generation', 'image-generation', 290),
  ('Video Generation', 'video-generation', 300);
